[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "openssl", "libffi", "zlib", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = [
    "python -m ensurepip",
    "python -m pip install --upgrade pip setuptools wheel",
    "python -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python main.py"

[variables]
PYTHONUNBUFFERED = "1"
